# Generated by Django 4.2.3 on 2023-07-19 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='national_number',
            field=models.IntegerField(null=True),
        ),
    ]
