# Generated by Django 4.2.3 on 2023-07-19 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_national_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='credit_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
    ]
