# Generated by Django 4.2.3 on 2023-07-20 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_student_groups_alter_student_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='family_book_number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='family_paper_number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='family_serial_number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='national_number',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
