# Generated by Django 4.2.3 on 2023-07-20 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_alter_enrollment_date_enrolled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='date_enrolled',
            field=models.DateField(auto_now_add=True),
        ),
    ]
