# Generated by Django 4.2.3 on 2023-07-20 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_alter_enrollment_date_enrolled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='day_of_week',
        ),
        migrations.AddField(
            model_name='lecture',
            name='title',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='lecturetime',
            name='day',
            field=models.CharField(choices=[('SU', 'SUNDAY'), ('MO', 'MONDAY'), ('TU', 'TUESDAY'), ('WE', 'WEDNESDAY'), ('TH', 'THURSDAY'), ('FR', 'FRIDAY'), ('SA', 'SATURDAY')], default='MO', max_length=2),
        ),
    ]
