# Generated by Django 4.2.3 on 2023-07-22 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_lecture_unites_semester_result_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='total_degree',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='unites',
        ),
        migrations.AlterField(
            model_name='student',
            name='current_semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_students', to='students.semester'),
        ),
    ]
