# Generated by Django 4.2.3 on 2023-07-22 12:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_remove_semester_total_degree_remove_semester_unites_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='semesters', to=settings.AUTH_USER_MODEL),
        ),
    ]
