# Generated by Django 4.2.3 on 2023-07-22 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_semesterresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semesterresult',
            name='subjects',
            field=models.ManyToManyField(default=None, to='students.result'),
        ),
    ]
